version: "3.8"

services:
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.build
    #   args:
    #     - CREATE_REDIS
    #     - PLATFORM
    image: iamrony777/javinfo-api:dev
    container_name: javinfo-api
    environment:
      - "BASE_URL=http://127.0.0.1:8000"
      - "INACTIVITY_TIMEOUT=60"
      - "HEALTHCHECK_PROVIDER=self"
      - "REDIS_URL=redis://default:${API_PASS}@db"
    env_file: 
      - .env
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    networks:
      - net
      
  db:
    image: redis
    container_name: redis
    entrypoint:
      [
        "redis-server",
        "--databases",
        "1",
        "--rdbcompression",
        "yes",
        "--dbfilename",
        "database-redis.rdb",
        "--dir",
        "/data",
        "--requirepass",
        "${API_PASS}",
        "--appendonly",
        "no",
        "--save",
        "60",
        "1",
        "--loglevel",
        "notice",
        "--timeout",
        "60"
      ]
    expose:
      - 6379/tcp
    networks:
      - net
    volumes:
      - data:/data:rw

networks:
  net:
    name: redis_network

volumes:
  data:
