  services:
  - type: web
    name: javinfo-api
    env: docker
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /api/check
    envVars:
    - key: PLATFORM
      value: render 
    - key: PORT
      value: 8000
    - key: CREATE_REDIS
      value: true
    - key: LOG_REQUEST
      value: false
    - key: API_USER
      sync: false
    - key: API_PASS
      sync: false
    - key: TZ
      value: UTC