#!/usr/bin/env python3
"""
crontab simulator
format => python3 cron.py "* * * * *" "/path/to/script"
"""
import os
import sys
from subprocess import Popen
from time import sleep

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
from api import logger


@logger.catch()
def execute(path: str) -> None:
    """Run following script"""
    if os.path.isfile(path):
        with Popen([sys.executable ,path]) as process:
            logger.debug(f"Background Process {process.args[-1]} is running, PID: {process.pid}")


@logger.catch()
def start(*args, **kwargs):
    """start running"""
    scheduler = BackgroundScheduler(timezone=os.getenv("TZ"))
    scheduler.add_job(*args, **kwargs)
    scheduler.start()
    while True:
        sleep(10)


if __name__ == "__main__":
    with logger.catch():
        param = sys.argv[1:]
        if len(param) > 0:
            start(
                execute,
                args=[param[1]],
                trigger=CronTrigger.from_crontab(param[0]),
                max_instances=1,
            )
        else:
            logger.warning('No valid cronjob found, exiting')
            sys.exit()
