#!/usr/bin/env python3

import os
import sys
from redis import Redis

def check_if_first_time() -> int:
    """Check if this instance is running for the first time in last 24hrs"""
    with Redis.from_url(
        os.getenv("REDIS_URL"),
        decode_responses=True,
        socket_timeout=10.00,
        socket_connect_timeout=10.00,
    ) as redis:
        if redis.get("fresh") is None:
            redis.set("fresh", "1", ex=84000)
            sys.exit(0)
        if int(redis.get("fresh")) == 1:
            sys.exit(1)


if __name__ == "__main__":
    check_if_first_time()
