#!/usr/bin/env python3

import os
import sys
from redis import Redis


# def get_readable_time(seconds: int) -> str:
#     result = ''
#     (days, remainder) = divmod(seconds, 86400)
#     days = int(days)
#     if days != 0:
#         result += f'{days}d'
#     (hours, remainder) = divmod(remainder, 3600)
#     hours = int(hours)
#     if hours != 0:
#         result += f'{hours}h'
#     (minutes, seconds) = divmod(remainder, 60)
#     minutes = int(minutes)
#     if minutes != 0:
#         result += f'{minutes}m'
#     seconds = int(seconds)
#     result += f'{seconds}s'
#     return result


def check_if_first_time() -> int:
    """Check if this instance is running for the first time in last 24hrs"""
    with Redis.from_url(os.getenv("REDIS_URL"),decode_responses=True) as redis:
        if redis.get("fresh") in [None, 0]:
            redis.set("fresh", "1", ex=84000)
            sys.exit(0)
        if int(redis.get("fresh")) == 1:
            sys.exit(1)

if __name__ == '__main__':
    check_if_first_time()
