name: docker-dev

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.build
          platforms: linux/amd64
          push: true
          tags: iamrony777/javinfo-api:dev
          cache-from: type=registry,ref=iamrony777/javinfo-api:${{ github.ref_name }}-cache
          cache-to: type=registry,ref=iamrony777/javinfo-api:${{ github.ref_name }}-cache,mode=max
          build-args: |
            PLATFORM=container
            CREATE_REDIS=false
